### ISSUE TITLE
Strawberry

### ISSUE THREAD

**Issue by jonaski** [latach/Configs#1]
Since there is no way to contact someone on github without their email listed, I'm creating an issue here.
I stumbled upon your clementine fork by accident and thought I let you know about my fork of Clementine called Strawberry, you can find it here: https://github.com/jonaski/strawberry
If you like it and like to get involved send me an e-mail (it's listed on my github page) and I can send you more detailed information about the project, my story, and why I created a fork.

**Comment by latach** [comment]
I noticed your fork a few weeks ago.

I was trying to create a strip down easy to modify version of clementine, after removing all of the features that I did not use.

After a few month I gave up due to the time it took to maintain everything. Tbh I decided it was a waste of time and this was when I went back to Mac.

This is not to mentiopn of the bugs in Clementine which were impossible for me to fix, like some of my albums not being seen by Clementine.

Good luck with yours! I don't use Clementine anymore.

**Comment by jonaski** [comment]
I see. Thanks.

**Comment by latach** [comment]
@jonaski Mate I forgot to mention that eventually I stopped using Clementine, and I moved to Rhythmbox. In total I have used Rhythmbox more, and found it to be much more stable and trustworthy than Clementine.

Rhythmbox might seem it doesn't have much features, but for example if you add the cover art plugin it becomes a completely different thing.

There's a new project that started a couple of years ago called Lollipop. I remember that I tried it once and it was very buggy. I can't seem to find it anymore on github, don't know why!

Thanks!

**Comment by jonaski** [comment]
I've tried Rhythmbox and most other players for linux. I'm not looking for a new player.
I'm pretty dedicated to Strawberry, I've spend alot of time on it and it is fully functional at this point. I'm very happy with the result. It also works on macos and windows.
Before I used Clementine I had been using Amarok 1.x from around the time I started using the computer to play all my music on flac that I had ripped from CD's. I have around 1250 CD's ripped to flac.
I still contribute some to clementine, but there seem to be less involvement from the original authors, and I disagree with some of the decisions and statements that have been made.
